[package]
name = "mdot-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.1.1"
dirs = "6.0.0"
fern = "0.7.1"
log = "0.4.29"
mlua = { version = "0.11.6", features = [ "lua54", "vendored"] }
